# NumPy

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1,2],[4,5],[6,7]]

In [5]:
np.array(nested_list)

array([[1, 2],
       [4, 5],
       [6, 7]])

In [7]:
np.arange(0,10,2) # start, stop, step

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3) # these are floating point numbers and thats why they are as 0. and somthing

array([0., 0., 0.])

In [11]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,10,3) # evenly spaced numbers. (3 evenly spaced numbers in between 0 and 10 inclusive)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [16]:
np.eye(5) # unit matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(4)

array([0.60266971, 0.07300989, 0.13435792, 0.08797097])

In [20]:
np.random.rand(3,4) # fake uniform distribution

array([[0.45363925, 0.53944017, 0.19152194, 0.84884993],
       [0.15317858, 0.77366997, 0.72901458, 0.17350838],
       [0.2411695 , 0.48720376, 0.47684051, 0.92525622]])

In [21]:
np.random.randn(1,2) # standard normal distribution mean = 0, variance = 1

array([[-0.46447723, -1.32995505]])

In [25]:
np.random.randint(1,100,(1,3)) #low(inclusive), high(exclusive), size

array([[92, 99, 31]], dtype=int32)

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
# reshape vectors

arr = np.arange(5)

In [29]:
arr

array([0, 1, 2, 3, 4])

In [30]:
ranarr = np.random.rand(5)

In [31]:
ranarr

array([0.15601864, 0.15599452, 0.05808361, 0.86617615, 0.60111501])

In [33]:
arr.shape

(5,)

In [35]:
arr = arr.reshape(5,1)

In [36]:
arr

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [40]:
arr.max()

np.int64(4)

In [39]:
arr.argmax()

np.int64(4)

In [42]:
arr.dtype

dtype('int64')