In [1]:
#environment

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid


Building a Neural Network with TensorFlow


In [2]:
#preparing training data
x_train = np.array([[90,5,2,3],[80,10,5,5],[70,10,3,17],[20,20,20,40]])
y_train = np.array([60,50,80,40])

Building a Neural Network with TensorFlow (Common Method)


In [3]:
model = Sequential([
    Dense(units = 8, activation='sigmoid', name='layer1'),  #layer 1
    Dense(units = 1, activation='sigmoid', name='layer2')  #layer 2
])

In [4]:
W1 = np.zeros((4,8))
b1 = np.zeros((4,1))
W2 = np.zeros((8,1))
b2 = np.zeros((1,1))

print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"W2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)

W1(4, 8):
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] 
b1(4, 1): [[0.]
 [0.]
 [0.]
 [0.]]
W2(8, 1):
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 
b2(1, 1): [[0.]]


In [5]:
#preparing training data
x_train = np.array([[90,5,2,3],[80,10,5,5],[70,10,3,17],[20,20,20,40]])
y_train = np.array([60,50,80,40])

In [6]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

model.fit(
    x_train,
    y_train,            
    epochs=10,
)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 1.2765
Epoch 2/10
1/1 [==============================] - 0s 15ms/step - loss: -1.2500
Epoch 3/10
1/1 [==============================] - 0s 24ms/step - loss: -3.9730
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: -7.0865
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: -10.8861
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: -15.6772
Epoch 7/10
1/1 [==============================] - 0s 0s/step - loss: -21.4837
Epoch 8/10
1/1 [==============================] - 0s 15ms/step - loss: -27.7210
Epoch 9/10
1/1 [==============================] - 0s 0s/step - loss: -33.4225
Epoch 10/10
1/1 [==============================] - 0s 14ms/step - loss: -38.1583


In [7]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)

W1:
 [[-0.34750903 -0.17201863 -0.2597354  -0.07948302 -0.4392262  -0.35063806
   0.386522    0.66776556]
 [-0.63888603  0.72168374 -0.14487436  0.16905186  0.32087788  0.23571053
   0.56205434 -0.1382948 ]
 [-0.06296754  0.4521141   0.25386629  0.4504937  -0.31182376 -0.5926968
   0.22226542 -0.416159  ]
 [-0.570184    0.39857864 -0.460649    0.2100121  -0.45505315 -0.50882125
   0.6906484   0.27303487]] 
b1: [-1.3688117e-10  8.8765800e-02 -1.0301565e-03 -9.3539812e-02
  1.6188839e-07  2.7627600e-08  0.0000000e+00  5.9694234e-02]
W2:
 [[-0.5799614 ]
 [ 0.83907914]
 [-0.48148388]
 [-0.09616147]
 [ 0.10166947]
 [ 0.69830453]
 [-0.2835673 ]
 [ 0.5386459 ]] 
b2: [0.09999046]


In [8]:
w = np.array([[1,-3,5],[2,4,-6]])

In [9]:
print(w[:,0])

[1 2]
