In [6]:
#evironment

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid


Explicit way of builidng layers

In [8]:
#input layer (layer 0)
x = np.array([[200,17]])

#layer 1
layer_1 = Dense(units=3, activation = 'sigmoid')
a1 = layer_1(x)

In [9]:
a1.numpy()

array([[0.0000000e+00, 1.6364962e-15, 1.0000000e+00]], dtype=float32)

In [13]:
layer_2 = Dense(units=1, activation='sigmoid')
a2 = layer_2(a1)

In [16]:
print(a2)

tf.Tensor([[0.38789332]], shape=(1, 1), dtype=float32)


In [17]:
#convert from tensorflow tensor to numpy array by,
a2.numpy()

array([[0.38789332]], dtype=float32)

Building a Neural Network with TensorFlow


In [18]:
layer_1 = Dense(units=3, activation='sigmoid')
layer_2 = Dense(units=1, activation='sigmoid')

model = Sequential([layer_1,layer_2])

In [20]:
#preparing training data
x_train = np.array([[90,5,2,3],[80,10,5,5],[70,10,3,17],[20,20,20,40]])
y_train = np.array([60,50,80,40])

Building a Neural Network with TensorFlow (Common Method)


In [94]:
model = Sequential([
    Dense(units = 8, activation='sigmoid', name='layer1'),  #layer 1
    Dense(units = 1, activation='sigmoid', name='layer2')  #layer 2
])

In [95]:
W1 = np.zeros((4,8))
b1 = np.zeros((4,1))
W2 = np.zeros((8,1))
b2 = np.zeros((1,1))

print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"W2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)

W1(4, 8):
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] 
b1(4, 1): [[0.]
 [0.]
 [0.]
 [0.]]
W2(8, 1):
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 
b2(1, 1): [[0.]]


In [96]:
#preparing training data
x_train = np.array([[90,5,2,3],[80,10,5,5],[70,10,3,17],[20,20,20,40]])
y_train = np.array([60,50,80,40])

In [97]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

model.fit(
    x_train,
    y_train,            
    epochs=10,
)

Epoch 1/10
1/1 [==============================] - 0s 359ms/step - loss: -26.6019
Epoch 2/10
1/1 [==============================] - 0s 17ms/step - loss: -30.5485
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: -34.7100
Epoch 4/10
1/1 [==============================] - 0s 664us/step - loss: -39.2945
Epoch 5/10
1/1 [==============================] - 0s 43ms/step - loss: -44.6030
Epoch 6/10
1/1 [==============================] - 0s 0s/step - loss: -50.8675
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: -57.8467
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: -64.7003
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: -70.8900
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: -76.9770


In [87]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)

W1:
 [[ 0.31901187  0.23883422  0.15481189  0.39689976]
 [ 0.8529909   0.09766833 -0.49980727  0.13404495]
 [-0.58497673  0.5145656   0.66331476  0.4459043 ]
 [ 0.33178896  0.05501869 -0.5081375   0.8133088 ]] 
b1: [0.         0.00161118 0.07901712 0.        ]
W2:
 [[-0.4163197]
 [ 0.3137244]
 [ 0.7785026]
 [-0.9287706]] 
b2: [0.09999251]


In [108]:
w = np.array([[1,-3,5],[2,4,-6]])

In [109]:
print(w[:,0])

[1 2]
